variable "tenant" {}
variable "name" {}
variable "environment" {}
variable "cidr_block" {}
variable "vpc_fl_cw_log" {}
variable "vpc_fl_s3_exp" {}
variable "nat_gateway" {}
variable "nat_count" {}
variable "nat_instance" {}
variable "nat_ami" {}
variable "pbl_sub_count" {}
variable "pvt_sub_count" {}
variable "eks_sub_count" {}
variable "db_sub_count" {}